### ISSUE TITLE
找不到镜像

### ISSUE THREAD

**Issue by amosbird** [jasonlix5/docker-cobbler#2]
你好，我将Centos7的iso mount到了/mnt目录下，然后执行docker-compose。但是到web console里看不到任何镜像。请问有详细一些的教程吗？谢谢！

**Comment by jasonlix5** [comment]
@amosbird docker环境起来后，只是一个空的cobbler环境，你需要使用cobbler import命令，把镜像导入到cobbler服务里后才能看到。建议你先查下cobbler使用文档。

**Comment by amosbird** [comment]
好的，但是这种东西能否直接做到docker-compose里呢？比如增加一个iso文件夹，然后compose up的时候，把所有里面的镜像都自动添加了

**Comment by jasonlix5** [comment]
@amosbird 这个还得看个人习惯，也不是所有镜像都会用到。这个镜像只是提供一个干净、原始的cobbler环境，具体怎么用，全看个人的配置。
