### ISSUE TITLE
No signature matched in /var/www/cobbler/ks_mirror/CentOS-7.3-x86_64 这是什么情况？

### ISSUE THREAD

**Issue by chenlingmin** [jasonlix5/docker-cobbler#3]
我运行 cobbler import --name=CentOS-7.3 --path=/mnt/ --arch=x86_64 导入镜像

**Comment by jasonlix5** [comment]
运行 cobbler signature update ，试下。

**Comment by chenlingmin** [comment]
没用😂

**Comment by chenlingmin** [comment]
我修改 `/var/lib/cobbler/distro_signatures.json` 都不行

**Comment by chenlingmin** [comment]
![image](https://user-images.githubusercontent.com/8233283/30848192-ea190086-a2d0-11e7-8776-4513e910b13f.png)

**Comment by jasonlix5** [comment]
supervisorctl restart cobblerd ， 重启cobblerd服务后试下呢。

**Comment by chenlingmin** [comment]
![image](https://user-images.githubusercontent.com/8233283/30848580-2d9a32fc-a2d2-11e7-82c1-4ff2ac12dfdf.png)

**Comment by chenlingmin** [comment]
这是我打的日志

**Comment by chenlingmin** [comment]
不是传 iso 镜像到 mnt 上面么？

**Comment by jasonlix5** [comment]
需要把iso镜像里的所有文件解压到mnt里面，不是把iso镜像文件放到mnt里。

**Comment by chenlingmin** [comment]
怪不得，翻了会他的代码

**Comment by chenlingmin** [comment]
怎么解压？

**Comment by jasonlix5** [comment]
随便挂在到一个目录：mount -o loop centos.iso /tmp/centos， 在copy到mnt下，copy完umount就行了。

**Comment by chenlingmin** [comment]
😂搞了一下午，可以了

**Comment by jasonlix5** [comment]
👏

**Comment by chenlingmin** [comment]
能加个 qq 微信么？ 还有些问题想问问你😄

**Comment by novakho** [comment]
> 随便挂在到一个目录：mount -o loop centos.iso /tmp/centos， 在copy到mnt下，copy完umount就行了。

copy到mnt后运行，还是一样的报错，我的环境是redhat7.9 cobbler是2.8.5，报错如下，帮忙看看
[root@localhost mnt]# cobbler import --name=Centos8.3 --arch=x86_64 --path=/mnt
task started: 2021-04-15_054105_import
task started (id=Media import, time=Thu Apr 15 05:41:05 2021)
Found a candidate signature: breed=suse, version=sles15generic
Found a candidate signature: breed=suse, version=opensuse15.0
Found a candidate signature: breed=suse, version=opensuse15.1
Found a candidate signature: breed=redhat, version=rhel8
No signature matched in /var/www/cobbler/ks_mirror/Centos8.3-x86_64
!!! TASK FAILED !!!
